version: "3"
services:
  graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    container_name: gateway  #コンテナの名前
    tty: true  #コンテナの永続化
    command: air
    ports:
      - '8080:8080'
    volumes:  #マウントディレクトリ
      - .:/app
    depends_on:
      - grpc

  proto:
    build:
      context: ./proto
      dockerfile: Dockerfile
    volumes:
      - .:/app
  
  grpc:
    build:
      context: ./grpc
      dockerfile: Dockerfile
    container_name: service
    tty: true
    volumes:
      - .:/app
  
  theater-db:
    image: mysql:8.0
    container_name: theater-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: theater
      MYSQL_USER: theater
      MYSQL_PASSWORD: theater
    ports:
      - "3306:3306"

  theater-api:
    build:
      context: ./theater-api
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASS}@graphql-db:3306/${DB_NAME}"
    depends_on:
      - graphql-db

  # connectお試し
  # connect-go-example:
  #   build:
  #     context: ./connect-go-example
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3001:3001"