version: "3"
services:
  gateway:  #サービス名
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway  #コンテナの名前
    tty: true  #コンテナの永続化
    ports:
      - '8080:8080'
    volumes:  #マウントディレクトリ
      - .:/app
